spring:
  profiles:
    active: local

logging:
  level:
    com.example.demo: debug
#    org.redisson : trace

nft:
  name: scam

---

spring:
  config:
    activate:
      on-profile: local

  redis:
    host: localhost
    port: 6379

  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:tcp://localhost/~/study

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        show_sql: true
        format_sql: true

---

spring:
  config:
    activate:
      on-profile: cloud

  redis:
    host: clustercfg.test-memorydb.sytn5f.memorydb.ap-northeast-2.amazonaws.com
    port: 6379
